apiVersion: v1
kind: ConfigMap
metadata:
  name: good-manager-config
  namespace: kube-system
data:
  service-conf: |
    config:
      hostname: "good-manager.npool.top"
      http_port: 50540
      grpc_port: 50541
      healthz_port: 50542
      prometheus_port: 50543
      appid: "89089012783789789719823798127398"
      serviceid: "6161ecc0-0b2c-11ed-b571-72e9de4b20f6"
      logdir: "./"
      apolloAccessKey: "0147fb70b815403790e8634b899fac07"
